package com.james.ssm.mapper;

import com.james.ssm.po.Memuleft;
import com.james.ssm.po.MemuleftExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemuleftMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memuleft
     *
     * @mbg.generated Wed Mar 28 15:28:11 CST 2018
     */
    long countByExample(MemuleftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memuleft
     *
     * @mbg.generated Wed Mar 28 15:28:11 CST 2018
     */
    int deleteByExample(MemuleftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memuleft
     *
     * @mbg.generated Wed Mar 28 15:28:11 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memuleft
     *
     * @mbg.generated Wed Mar 28 15:28:11 CST 2018
     */
    int insert(Memuleft record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memuleft
     *
     * @mbg.generated Wed Mar 28 15:28:11 CST 2018
     */
    int insertSelective(Memuleft record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memuleft
     *
     * @mbg.generated Wed Mar 28 15:28:11 CST 2018
     */
    List<Memuleft> selectByExample(MemuleftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memuleft
     *
     * @mbg.generated Wed Mar 28 15:28:11 CST 2018
     */
    Memuleft selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memuleft
     *
     * @mbg.generated Wed Mar 28 15:28:11 CST 2018
     */
    int updateByExampleSelective(@Param("record") Memuleft record, @Param("example") MemuleftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memuleft
     *
     * @mbg.generated Wed Mar 28 15:28:11 CST 2018
     */
    int updateByExample(@Param("record") Memuleft record, @Param("example") MemuleftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memuleft
     *
     * @mbg.generated Wed Mar 28 15:28:11 CST 2018
     */
    int updateByPrimaryKeySelective(Memuleft record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memuleft
     *
     * @mbg.generated Wed Mar 28 15:28:11 CST 2018
     */
    int updateByPrimaryKey(Memuleft record);
}