package com.james.ssm.mapper;

import com.james.ssm.po.Rolspermission;
import com.james.ssm.po.RolspermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RolspermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolspermission
     *
     * @mbg.generated Wed Mar 28 15:11:08 CST 2018
     */
    long countByExample(RolspermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolspermission
     *
     * @mbg.generated Wed Mar 28 15:11:08 CST 2018
     */
    int deleteByExample(RolspermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolspermission
     *
     * @mbg.generated Wed Mar 28 15:11:08 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolspermission
     *
     * @mbg.generated Wed Mar 28 15:11:08 CST 2018
     */
    int insert(Rolspermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolspermission
     *
     * @mbg.generated Wed Mar 28 15:11:08 CST 2018
     */
    int insertSelective(Rolspermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolspermission
     *
     * @mbg.generated Wed Mar 28 15:11:08 CST 2018
     */
    List<Rolspermission> selectByExample(RolspermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolspermission
     *
     * @mbg.generated Wed Mar 28 15:11:08 CST 2018
     */
    Rolspermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolspermission
     *
     * @mbg.generated Wed Mar 28 15:11:08 CST 2018
     */
    int updateByExampleSelective(@Param("record") Rolspermission record, @Param("example") RolspermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolspermission
     *
     * @mbg.generated Wed Mar 28 15:11:08 CST 2018
     */
    int updateByExample(@Param("record") Rolspermission record, @Param("example") RolspermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolspermission
     *
     * @mbg.generated Wed Mar 28 15:11:08 CST 2018
     */
    int updateByPrimaryKeySelective(Rolspermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolspermission
     *
     * @mbg.generated Wed Mar 28 15:11:08 CST 2018
     */
    int updateByPrimaryKey(Rolspermission record);
}