package com.james.ssm.mapper;

import com.james.ssm.po.Systeminfo;
import com.james.ssm.po.SysteminfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysteminfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEMINFO
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    long countByExample(SysteminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEMINFO
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    int deleteByExample(SysteminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEMINFO
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEMINFO
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    int insert(Systeminfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEMINFO
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    int insertSelective(Systeminfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEMINFO
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    List<Systeminfo> selectByExample(SysteminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEMINFO
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    Systeminfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEMINFO
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") Systeminfo record, @Param("example") SysteminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEMINFO
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    int updateByExample(@Param("record") Systeminfo record, @Param("example") SysteminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEMINFO
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    int updateByPrimaryKeySelective(Systeminfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEMINFO
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    int updateByPrimaryKey(Systeminfo record);
}