package com.james.ssm.mapper;

import com.james.ssm.po.Watchtask;
import com.james.ssm.po.WatchtaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WatchtaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WATCHTASK
     *
     * @mbg.generated Mon Mar 05 18:31:46 CST 2018
     */
    long countByExample(WatchtaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WATCHTASK
     *
     * @mbg.generated Mon Mar 05 18:31:46 CST 2018
     */
    int deleteByExample(WatchtaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WATCHTASK
     *
     * @mbg.generated Mon Mar 05 18:31:46 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WATCHTASK
     *
     * @mbg.generated Mon Mar 05 18:31:46 CST 2018
     */
    int insert(Watchtask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WATCHTASK
     *
     * @mbg.generated Mon Mar 05 18:31:46 CST 2018
     */
    int insertSelective(Watchtask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WATCHTASK
     *
     * @mbg.generated Mon Mar 05 18:31:46 CST 2018
     */
    List<Watchtask> selectByExample(WatchtaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WATCHTASK
     *
     * @mbg.generated Mon Mar 05 18:31:46 CST 2018
     */
    Watchtask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WATCHTASK
     *
     * @mbg.generated Mon Mar 05 18:31:46 CST 2018
     */
    int updateByExampleSelective(@Param("record") Watchtask record, @Param("example") WatchtaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WATCHTASK
     *
     * @mbg.generated Mon Mar 05 18:31:46 CST 2018
     */
    int updateByExample(@Param("record") Watchtask record, @Param("example") WatchtaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WATCHTASK
     *
     * @mbg.generated Mon Mar 05 18:31:46 CST 2018
     */
    int updateByPrimaryKeySelective(Watchtask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WATCHTASK
     *
     * @mbg.generated Mon Mar 05 18:31:46 CST 2018
     */
    int updateByPrimaryKey(Watchtask record);
}