package com.james.ssm.po;

public class Inspection {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSPECTION.ID
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSPECTION.INSPECTIONID
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    private String inspectionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSPECTION.INSPECTIONCONTEXT
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    private String inspectioncontext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSPECTION.INSPECTIONCYCLE
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    private String inspectioncycle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSPECTION.INSPECTIONCYCLEMAN
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    private Integer inspectioncycleman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSPECTION.COMMENT
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSPECTION.INSPECTIONWATCHMAN
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    private Integer inspectionwatchman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSPECTION.INSPECTIONSUPPORTMAN
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    private String inspectionsupportman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSPECTION.MONDAY
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    private byte[] monday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSPECTION.TUESDAY
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    private byte[] tuesday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSPECTION.THURSDAY
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    private byte[] thursday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSPECTION.WENNESDAY
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    private byte[] wennesday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSPECTION.FIRDAY
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    private byte[] firday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSPECTION.SATURDAY
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    private byte[] saturday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSPECTION.SUNDAY
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    private byte[] sunday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSPECTION.INSPECTIONSYSTEMID
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    private Integer inspectionsystemid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSPECTION.ID
     *
     * @return the value of INSPECTION.ID
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSPECTION.ID
     *
     * @param id the value for INSPECTION.ID
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSPECTION.INSPECTIONID
     *
     * @return the value of INSPECTION.INSPECTIONID
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public String getInspectionid() {
        return inspectionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSPECTION.INSPECTIONID
     *
     * @param inspectionid the value for INSPECTION.INSPECTIONID
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setInspectionid(String inspectionid) {
        this.inspectionid = inspectionid == null ? null : inspectionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSPECTION.INSPECTIONCONTEXT
     *
     * @return the value of INSPECTION.INSPECTIONCONTEXT
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public String getInspectioncontext() {
        return inspectioncontext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSPECTION.INSPECTIONCONTEXT
     *
     * @param inspectioncontext the value for INSPECTION.INSPECTIONCONTEXT
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setInspectioncontext(String inspectioncontext) {
        this.inspectioncontext = inspectioncontext == null ? null : inspectioncontext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSPECTION.INSPECTIONCYCLE
     *
     * @return the value of INSPECTION.INSPECTIONCYCLE
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public String getInspectioncycle() {
        return inspectioncycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSPECTION.INSPECTIONCYCLE
     *
     * @param inspectioncycle the value for INSPECTION.INSPECTIONCYCLE
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setInspectioncycle(String inspectioncycle) {
        this.inspectioncycle = inspectioncycle == null ? null : inspectioncycle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSPECTION.INSPECTIONCYCLEMAN
     *
     * @return the value of INSPECTION.INSPECTIONCYCLEMAN
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public Integer getInspectioncycleman() {
        return inspectioncycleman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSPECTION.INSPECTIONCYCLEMAN
     *
     * @param inspectioncycleman the value for INSPECTION.INSPECTIONCYCLEMAN
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setInspectioncycleman(Integer inspectioncycleman) {
        this.inspectioncycleman = inspectioncycleman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSPECTION.COMMENT
     *
     * @return the value of INSPECTION.COMMENT
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSPECTION.COMMENT
     *
     * @param comment the value for INSPECTION.COMMENT
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSPECTION.INSPECTIONWATCHMAN
     *
     * @return the value of INSPECTION.INSPECTIONWATCHMAN
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public Integer getInspectionwatchman() {
        return inspectionwatchman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSPECTION.INSPECTIONWATCHMAN
     *
     * @param inspectionwatchman the value for INSPECTION.INSPECTIONWATCHMAN
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setInspectionwatchman(Integer inspectionwatchman) {
        this.inspectionwatchman = inspectionwatchman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSPECTION.INSPECTIONSUPPORTMAN
     *
     * @return the value of INSPECTION.INSPECTIONSUPPORTMAN
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public String getInspectionsupportman() {
        return inspectionsupportman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSPECTION.INSPECTIONSUPPORTMAN
     *
     * @param inspectionsupportman the value for INSPECTION.INSPECTIONSUPPORTMAN
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setInspectionsupportman(String inspectionsupportman) {
        this.inspectionsupportman = inspectionsupportman == null ? null : inspectionsupportman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSPECTION.MONDAY
     *
     * @return the value of INSPECTION.MONDAY
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public byte[] getMonday() {
        return monday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSPECTION.MONDAY
     *
     * @param monday the value for INSPECTION.MONDAY
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setMonday(byte[] monday) {
        this.monday = monday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSPECTION.TUESDAY
     *
     * @return the value of INSPECTION.TUESDAY
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public byte[] getTuesday() {
        return tuesday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSPECTION.TUESDAY
     *
     * @param tuesday the value for INSPECTION.TUESDAY
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setTuesday(byte[] tuesday) {
        this.tuesday = tuesday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSPECTION.THURSDAY
     *
     * @return the value of INSPECTION.THURSDAY
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public byte[] getThursday() {
        return thursday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSPECTION.THURSDAY
     *
     * @param thursday the value for INSPECTION.THURSDAY
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setThursday(byte[] thursday) {
        this.thursday = thursday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSPECTION.WENNESDAY
     *
     * @return the value of INSPECTION.WENNESDAY
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public byte[] getWennesday() {
        return wennesday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSPECTION.WENNESDAY
     *
     * @param wennesday the value for INSPECTION.WENNESDAY
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setWennesday(byte[] wennesday) {
        this.wennesday = wennesday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSPECTION.FIRDAY
     *
     * @return the value of INSPECTION.FIRDAY
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public byte[] getFirday() {
        return firday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSPECTION.FIRDAY
     *
     * @param firday the value for INSPECTION.FIRDAY
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setFirday(byte[] firday) {
        this.firday = firday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSPECTION.SATURDAY
     *
     * @return the value of INSPECTION.SATURDAY
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public byte[] getSaturday() {
        return saturday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSPECTION.SATURDAY
     *
     * @param saturday the value for INSPECTION.SATURDAY
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setSaturday(byte[] saturday) {
        this.saturday = saturday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSPECTION.SUNDAY
     *
     * @return the value of INSPECTION.SUNDAY
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public byte[] getSunday() {
        return sunday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSPECTION.SUNDAY
     *
     * @param sunday the value for INSPECTION.SUNDAY
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setSunday(byte[] sunday) {
        this.sunday = sunday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSPECTION.INSPECTIONSYSTEMID
     *
     * @return the value of INSPECTION.INSPECTIONSYSTEMID
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public Integer getInspectionsystemid() {
        return inspectionsystemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSPECTION.INSPECTIONSYSTEMID
     *
     * @param inspectionsystemid the value for INSPECTION.INSPECTIONSYSTEMID
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setInspectionsystemid(Integer inspectionsystemid) {
        this.inspectionsystemid = inspectionsystemid;
    }
}