package com.james.ssm.po;

import java.util.ArrayList;
import java.util.List;

public class InspectionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INSPECTION
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INSPECTION
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INSPECTION
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECTION
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public InspectionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECTION
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECTION
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECTION
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECTION
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECTION
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECTION
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECTION
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECTION
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECTION
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECTION
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INSPECTION
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andInspectionidIsNull() {
            addCriterion("INSPECTIONID is null");
            return (Criteria) this;
        }

        public Criteria andInspectionidIsNotNull() {
            addCriterion("INSPECTIONID is not null");
            return (Criteria) this;
        }

        public Criteria andInspectionidEqualTo(String value) {
            addCriterion("INSPECTIONID =", value, "inspectionid");
            return (Criteria) this;
        }

        public Criteria andInspectionidNotEqualTo(String value) {
            addCriterion("INSPECTIONID <>", value, "inspectionid");
            return (Criteria) this;
        }

        public Criteria andInspectionidGreaterThan(String value) {
            addCriterion("INSPECTIONID >", value, "inspectionid");
            return (Criteria) this;
        }

        public Criteria andInspectionidGreaterThanOrEqualTo(String value) {
            addCriterion("INSPECTIONID >=", value, "inspectionid");
            return (Criteria) this;
        }

        public Criteria andInspectionidLessThan(String value) {
            addCriterion("INSPECTIONID <", value, "inspectionid");
            return (Criteria) this;
        }

        public Criteria andInspectionidLessThanOrEqualTo(String value) {
            addCriterion("INSPECTIONID <=", value, "inspectionid");
            return (Criteria) this;
        }

        public Criteria andInspectionidLike(String value) {
            addCriterion("INSPECTIONID like", value, "inspectionid");
            return (Criteria) this;
        }

        public Criteria andInspectionidNotLike(String value) {
            addCriterion("INSPECTIONID not like", value, "inspectionid");
            return (Criteria) this;
        }

        public Criteria andInspectionidIn(List<String> values) {
            addCriterion("INSPECTIONID in", values, "inspectionid");
            return (Criteria) this;
        }

        public Criteria andInspectionidNotIn(List<String> values) {
            addCriterion("INSPECTIONID not in", values, "inspectionid");
            return (Criteria) this;
        }

        public Criteria andInspectionidBetween(String value1, String value2) {
            addCriterion("INSPECTIONID between", value1, value2, "inspectionid");
            return (Criteria) this;
        }

        public Criteria andInspectionidNotBetween(String value1, String value2) {
            addCriterion("INSPECTIONID not between", value1, value2, "inspectionid");
            return (Criteria) this;
        }

        public Criteria andInspectioncontextIsNull() {
            addCriterion("INSPECTIONCONTEXT is null");
            return (Criteria) this;
        }

        public Criteria andInspectioncontextIsNotNull() {
            addCriterion("INSPECTIONCONTEXT is not null");
            return (Criteria) this;
        }

        public Criteria andInspectioncontextEqualTo(String value) {
            addCriterion("INSPECTIONCONTEXT =", value, "inspectioncontext");
            return (Criteria) this;
        }

        public Criteria andInspectioncontextNotEqualTo(String value) {
            addCriterion("INSPECTIONCONTEXT <>", value, "inspectioncontext");
            return (Criteria) this;
        }

        public Criteria andInspectioncontextGreaterThan(String value) {
            addCriterion("INSPECTIONCONTEXT >", value, "inspectioncontext");
            return (Criteria) this;
        }

        public Criteria andInspectioncontextGreaterThanOrEqualTo(String value) {
            addCriterion("INSPECTIONCONTEXT >=", value, "inspectioncontext");
            return (Criteria) this;
        }

        public Criteria andInspectioncontextLessThan(String value) {
            addCriterion("INSPECTIONCONTEXT <", value, "inspectioncontext");
            return (Criteria) this;
        }

        public Criteria andInspectioncontextLessThanOrEqualTo(String value) {
            addCriterion("INSPECTIONCONTEXT <=", value, "inspectioncontext");
            return (Criteria) this;
        }

        public Criteria andInspectioncontextLike(String value) {
            addCriterion("INSPECTIONCONTEXT like", value, "inspectioncontext");
            return (Criteria) this;
        }

        public Criteria andInspectioncontextNotLike(String value) {
            addCriterion("INSPECTIONCONTEXT not like", value, "inspectioncontext");
            return (Criteria) this;
        }

        public Criteria andInspectioncontextIn(List<String> values) {
            addCriterion("INSPECTIONCONTEXT in", values, "inspectioncontext");
            return (Criteria) this;
        }

        public Criteria andInspectioncontextNotIn(List<String> values) {
            addCriterion("INSPECTIONCONTEXT not in", values, "inspectioncontext");
            return (Criteria) this;
        }

        public Criteria andInspectioncontextBetween(String value1, String value2) {
            addCriterion("INSPECTIONCONTEXT between", value1, value2, "inspectioncontext");
            return (Criteria) this;
        }

        public Criteria andInspectioncontextNotBetween(String value1, String value2) {
            addCriterion("INSPECTIONCONTEXT not between", value1, value2, "inspectioncontext");
            return (Criteria) this;
        }

        public Criteria andInspectioncycleIsNull() {
            addCriterion("INSPECTIONCYCLE is null");
            return (Criteria) this;
        }

        public Criteria andInspectioncycleIsNotNull() {
            addCriterion("INSPECTIONCYCLE is not null");
            return (Criteria) this;
        }

        public Criteria andInspectioncycleEqualTo(String value) {
            addCriterion("INSPECTIONCYCLE =", value, "inspectioncycle");
            return (Criteria) this;
        }

        public Criteria andInspectioncycleNotEqualTo(String value) {
            addCriterion("INSPECTIONCYCLE <>", value, "inspectioncycle");
            return (Criteria) this;
        }

        public Criteria andInspectioncycleGreaterThan(String value) {
            addCriterion("INSPECTIONCYCLE >", value, "inspectioncycle");
            return (Criteria) this;
        }

        public Criteria andInspectioncycleGreaterThanOrEqualTo(String value) {
            addCriterion("INSPECTIONCYCLE >=", value, "inspectioncycle");
            return (Criteria) this;
        }

        public Criteria andInspectioncycleLessThan(String value) {
            addCriterion("INSPECTIONCYCLE <", value, "inspectioncycle");
            return (Criteria) this;
        }

        public Criteria andInspectioncycleLessThanOrEqualTo(String value) {
            addCriterion("INSPECTIONCYCLE <=", value, "inspectioncycle");
            return (Criteria) this;
        }

        public Criteria andInspectioncycleLike(String value) {
            addCriterion("INSPECTIONCYCLE like", value, "inspectioncycle");
            return (Criteria) this;
        }

        public Criteria andInspectioncycleNotLike(String value) {
            addCriterion("INSPECTIONCYCLE not like", value, "inspectioncycle");
            return (Criteria) this;
        }

        public Criteria andInspectioncycleIn(List<String> values) {
            addCriterion("INSPECTIONCYCLE in", values, "inspectioncycle");
            return (Criteria) this;
        }

        public Criteria andInspectioncycleNotIn(List<String> values) {
            addCriterion("INSPECTIONCYCLE not in", values, "inspectioncycle");
            return (Criteria) this;
        }

        public Criteria andInspectioncycleBetween(String value1, String value2) {
            addCriterion("INSPECTIONCYCLE between", value1, value2, "inspectioncycle");
            return (Criteria) this;
        }

        public Criteria andInspectioncycleNotBetween(String value1, String value2) {
            addCriterion("INSPECTIONCYCLE not between", value1, value2, "inspectioncycle");
            return (Criteria) this;
        }

        public Criteria andInspectioncyclemanIsNull() {
            addCriterion("INSPECTIONCYCLEMAN is null");
            return (Criteria) this;
        }

        public Criteria andInspectioncyclemanIsNotNull() {
            addCriterion("INSPECTIONCYCLEMAN is not null");
            return (Criteria) this;
        }

        public Criteria andInspectioncyclemanEqualTo(Integer value) {
            addCriterion("INSPECTIONCYCLEMAN =", value, "inspectioncycleman");
            return (Criteria) this;
        }

        public Criteria andInspectioncyclemanNotEqualTo(Integer value) {
            addCriterion("INSPECTIONCYCLEMAN <>", value, "inspectioncycleman");
            return (Criteria) this;
        }

        public Criteria andInspectioncyclemanGreaterThan(Integer value) {
            addCriterion("INSPECTIONCYCLEMAN >", value, "inspectioncycleman");
            return (Criteria) this;
        }

        public Criteria andInspectioncyclemanGreaterThanOrEqualTo(Integer value) {
            addCriterion("INSPECTIONCYCLEMAN >=", value, "inspectioncycleman");
            return (Criteria) this;
        }

        public Criteria andInspectioncyclemanLessThan(Integer value) {
            addCriterion("INSPECTIONCYCLEMAN <", value, "inspectioncycleman");
            return (Criteria) this;
        }

        public Criteria andInspectioncyclemanLessThanOrEqualTo(Integer value) {
            addCriterion("INSPECTIONCYCLEMAN <=", value, "inspectioncycleman");
            return (Criteria) this;
        }

        public Criteria andInspectioncyclemanIn(List<Integer> values) {
            addCriterion("INSPECTIONCYCLEMAN in", values, "inspectioncycleman");
            return (Criteria) this;
        }

        public Criteria andInspectioncyclemanNotIn(List<Integer> values) {
            addCriterion("INSPECTIONCYCLEMAN not in", values, "inspectioncycleman");
            return (Criteria) this;
        }

        public Criteria andInspectioncyclemanBetween(Integer value1, Integer value2) {
            addCriterion("INSPECTIONCYCLEMAN between", value1, value2, "inspectioncycleman");
            return (Criteria) this;
        }

        public Criteria andInspectioncyclemanNotBetween(Integer value1, Integer value2) {
            addCriterion("INSPECTIONCYCLEMAN not between", value1, value2, "inspectioncycleman");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("COMMENT is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("COMMENT is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("COMMENT =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("COMMENT <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("COMMENT >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("COMMENT >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("COMMENT <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("COMMENT <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("COMMENT like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("COMMENT not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("COMMENT in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("COMMENT not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("COMMENT between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("COMMENT not between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andInspectionwatchmanIsNull() {
            addCriterion("INSPECTIONWATCHMAN is null");
            return (Criteria) this;
        }

        public Criteria andInspectionwatchmanIsNotNull() {
            addCriterion("INSPECTIONWATCHMAN is not null");
            return (Criteria) this;
        }

        public Criteria andInspectionwatchmanEqualTo(Integer value) {
            addCriterion("INSPECTIONWATCHMAN =", value, "inspectionwatchman");
            return (Criteria) this;
        }

        public Criteria andInspectionwatchmanNotEqualTo(Integer value) {
            addCriterion("INSPECTIONWATCHMAN <>", value, "inspectionwatchman");
            return (Criteria) this;
        }

        public Criteria andInspectionwatchmanGreaterThan(Integer value) {
            addCriterion("INSPECTIONWATCHMAN >", value, "inspectionwatchman");
            return (Criteria) this;
        }

        public Criteria andInspectionwatchmanGreaterThanOrEqualTo(Integer value) {
            addCriterion("INSPECTIONWATCHMAN >=", value, "inspectionwatchman");
            return (Criteria) this;
        }

        public Criteria andInspectionwatchmanLessThan(Integer value) {
            addCriterion("INSPECTIONWATCHMAN <", value, "inspectionwatchman");
            return (Criteria) this;
        }

        public Criteria andInspectionwatchmanLessThanOrEqualTo(Integer value) {
            addCriterion("INSPECTIONWATCHMAN <=", value, "inspectionwatchman");
            return (Criteria) this;
        }

        public Criteria andInspectionwatchmanIn(List<Integer> values) {
            addCriterion("INSPECTIONWATCHMAN in", values, "inspectionwatchman");
            return (Criteria) this;
        }

        public Criteria andInspectionwatchmanNotIn(List<Integer> values) {
            addCriterion("INSPECTIONWATCHMAN not in", values, "inspectionwatchman");
            return (Criteria) this;
        }

        public Criteria andInspectionwatchmanBetween(Integer value1, Integer value2) {
            addCriterion("INSPECTIONWATCHMAN between", value1, value2, "inspectionwatchman");
            return (Criteria) this;
        }

        public Criteria andInspectionwatchmanNotBetween(Integer value1, Integer value2) {
            addCriterion("INSPECTIONWATCHMAN not between", value1, value2, "inspectionwatchman");
            return (Criteria) this;
        }

        public Criteria andInspectionsupportmanIsNull() {
            addCriterion("INSPECTIONSUPPORTMAN is null");
            return (Criteria) this;
        }

        public Criteria andInspectionsupportmanIsNotNull() {
            addCriterion("INSPECTIONSUPPORTMAN is not null");
            return (Criteria) this;
        }

        public Criteria andInspectionsupportmanEqualTo(String value) {
            addCriterion("INSPECTIONSUPPORTMAN =", value, "inspectionsupportman");
            return (Criteria) this;
        }

        public Criteria andInspectionsupportmanNotEqualTo(String value) {
            addCriterion("INSPECTIONSUPPORTMAN <>", value, "inspectionsupportman");
            return (Criteria) this;
        }

        public Criteria andInspectionsupportmanGreaterThan(String value) {
            addCriterion("INSPECTIONSUPPORTMAN >", value, "inspectionsupportman");
            return (Criteria) this;
        }

        public Criteria andInspectionsupportmanGreaterThanOrEqualTo(String value) {
            addCriterion("INSPECTIONSUPPORTMAN >=", value, "inspectionsupportman");
            return (Criteria) this;
        }

        public Criteria andInspectionsupportmanLessThan(String value) {
            addCriterion("INSPECTIONSUPPORTMAN <", value, "inspectionsupportman");
            return (Criteria) this;
        }

        public Criteria andInspectionsupportmanLessThanOrEqualTo(String value) {
            addCriterion("INSPECTIONSUPPORTMAN <=", value, "inspectionsupportman");
            return (Criteria) this;
        }

        public Criteria andInspectionsupportmanLike(String value) {
            addCriterion("INSPECTIONSUPPORTMAN like", value, "inspectionsupportman");
            return (Criteria) this;
        }

        public Criteria andInspectionsupportmanNotLike(String value) {
            addCriterion("INSPECTIONSUPPORTMAN not like", value, "inspectionsupportman");
            return (Criteria) this;
        }

        public Criteria andInspectionsupportmanIn(List<String> values) {
            addCriterion("INSPECTIONSUPPORTMAN in", values, "inspectionsupportman");
            return (Criteria) this;
        }

        public Criteria andInspectionsupportmanNotIn(List<String> values) {
            addCriterion("INSPECTIONSUPPORTMAN not in", values, "inspectionsupportman");
            return (Criteria) this;
        }

        public Criteria andInspectionsupportmanBetween(String value1, String value2) {
            addCriterion("INSPECTIONSUPPORTMAN between", value1, value2, "inspectionsupportman");
            return (Criteria) this;
        }

        public Criteria andInspectionsupportmanNotBetween(String value1, String value2) {
            addCriterion("INSPECTIONSUPPORTMAN not between", value1, value2, "inspectionsupportman");
            return (Criteria) this;
        }

        public Criteria andMondayIsNull() {
            addCriterion("MONDAY is null");
            return (Criteria) this;
        }

        public Criteria andMondayIsNotNull() {
            addCriterion("MONDAY is not null");
            return (Criteria) this;
        }

        public Criteria andMondayEqualTo(byte[] value) {
            addCriterion("MONDAY =", value, "monday");
            return (Criteria) this;
        }

        public Criteria andMondayNotEqualTo(byte[] value) {
            addCriterion("MONDAY <>", value, "monday");
            return (Criteria) this;
        }

        public Criteria andMondayGreaterThan(byte[] value) {
            addCriterion("MONDAY >", value, "monday");
            return (Criteria) this;
        }

        public Criteria andMondayGreaterThanOrEqualTo(byte[] value) {
            addCriterion("MONDAY >=", value, "monday");
            return (Criteria) this;
        }

        public Criteria andMondayLessThan(byte[] value) {
            addCriterion("MONDAY <", value, "monday");
            return (Criteria) this;
        }

        public Criteria andMondayLessThanOrEqualTo(byte[] value) {
            addCriterion("MONDAY <=", value, "monday");
            return (Criteria) this;
        }

        public Criteria andMondayIn(List<byte[]> values) {
            addCriterion("MONDAY in", values, "monday");
            return (Criteria) this;
        }

        public Criteria andMondayNotIn(List<byte[]> values) {
            addCriterion("MONDAY not in", values, "monday");
            return (Criteria) this;
        }

        public Criteria andMondayBetween(byte[] value1, byte[] value2) {
            addCriterion("MONDAY between", value1, value2, "monday");
            return (Criteria) this;
        }

        public Criteria andMondayNotBetween(byte[] value1, byte[] value2) {
            addCriterion("MONDAY not between", value1, value2, "monday");
            return (Criteria) this;
        }

        public Criteria andTuesdayIsNull() {
            addCriterion("TUESDAY is null");
            return (Criteria) this;
        }

        public Criteria andTuesdayIsNotNull() {
            addCriterion("TUESDAY is not null");
            return (Criteria) this;
        }

        public Criteria andTuesdayEqualTo(byte[] value) {
            addCriterion("TUESDAY =", value, "tuesday");
            return (Criteria) this;
        }

        public Criteria andTuesdayNotEqualTo(byte[] value) {
            addCriterion("TUESDAY <>", value, "tuesday");
            return (Criteria) this;
        }

        public Criteria andTuesdayGreaterThan(byte[] value) {
            addCriterion("TUESDAY >", value, "tuesday");
            return (Criteria) this;
        }

        public Criteria andTuesdayGreaterThanOrEqualTo(byte[] value) {
            addCriterion("TUESDAY >=", value, "tuesday");
            return (Criteria) this;
        }

        public Criteria andTuesdayLessThan(byte[] value) {
            addCriterion("TUESDAY <", value, "tuesday");
            return (Criteria) this;
        }

        public Criteria andTuesdayLessThanOrEqualTo(byte[] value) {
            addCriterion("TUESDAY <=", value, "tuesday");
            return (Criteria) this;
        }

        public Criteria andTuesdayIn(List<byte[]> values) {
            addCriterion("TUESDAY in", values, "tuesday");
            return (Criteria) this;
        }

        public Criteria andTuesdayNotIn(List<byte[]> values) {
            addCriterion("TUESDAY not in", values, "tuesday");
            return (Criteria) this;
        }

        public Criteria andTuesdayBetween(byte[] value1, byte[] value2) {
            addCriterion("TUESDAY between", value1, value2, "tuesday");
            return (Criteria) this;
        }

        public Criteria andTuesdayNotBetween(byte[] value1, byte[] value2) {
            addCriterion("TUESDAY not between", value1, value2, "tuesday");
            return (Criteria) this;
        }

        public Criteria andThursdayIsNull() {
            addCriterion("THURSDAY is null");
            return (Criteria) this;
        }

        public Criteria andThursdayIsNotNull() {
            addCriterion("THURSDAY is not null");
            return (Criteria) this;
        }

        public Criteria andThursdayEqualTo(byte[] value) {
            addCriterion("THURSDAY =", value, "thursday");
            return (Criteria) this;
        }

        public Criteria andThursdayNotEqualTo(byte[] value) {
            addCriterion("THURSDAY <>", value, "thursday");
            return (Criteria) this;
        }

        public Criteria andThursdayGreaterThan(byte[] value) {
            addCriterion("THURSDAY >", value, "thursday");
            return (Criteria) this;
        }

        public Criteria andThursdayGreaterThanOrEqualTo(byte[] value) {
            addCriterion("THURSDAY >=", value, "thursday");
            return (Criteria) this;
        }

        public Criteria andThursdayLessThan(byte[] value) {
            addCriterion("THURSDAY <", value, "thursday");
            return (Criteria) this;
        }

        public Criteria andThursdayLessThanOrEqualTo(byte[] value) {
            addCriterion("THURSDAY <=", value, "thursday");
            return (Criteria) this;
        }

        public Criteria andThursdayIn(List<byte[]> values) {
            addCriterion("THURSDAY in", values, "thursday");
            return (Criteria) this;
        }

        public Criteria andThursdayNotIn(List<byte[]> values) {
            addCriterion("THURSDAY not in", values, "thursday");
            return (Criteria) this;
        }

        public Criteria andThursdayBetween(byte[] value1, byte[] value2) {
            addCriterion("THURSDAY between", value1, value2, "thursday");
            return (Criteria) this;
        }

        public Criteria andThursdayNotBetween(byte[] value1, byte[] value2) {
            addCriterion("THURSDAY not between", value1, value2, "thursday");
            return (Criteria) this;
        }

        public Criteria andWennesdayIsNull() {
            addCriterion("WENNESDAY is null");
            return (Criteria) this;
        }

        public Criteria andWennesdayIsNotNull() {
            addCriterion("WENNESDAY is not null");
            return (Criteria) this;
        }

        public Criteria andWennesdayEqualTo(byte[] value) {
            addCriterion("WENNESDAY =", value, "wennesday");
            return (Criteria) this;
        }

        public Criteria andWennesdayNotEqualTo(byte[] value) {
            addCriterion("WENNESDAY <>", value, "wennesday");
            return (Criteria) this;
        }

        public Criteria andWennesdayGreaterThan(byte[] value) {
            addCriterion("WENNESDAY >", value, "wennesday");
            return (Criteria) this;
        }

        public Criteria andWennesdayGreaterThanOrEqualTo(byte[] value) {
            addCriterion("WENNESDAY >=", value, "wennesday");
            return (Criteria) this;
        }

        public Criteria andWennesdayLessThan(byte[] value) {
            addCriterion("WENNESDAY <", value, "wennesday");
            return (Criteria) this;
        }

        public Criteria andWennesdayLessThanOrEqualTo(byte[] value) {
            addCriterion("WENNESDAY <=", value, "wennesday");
            return (Criteria) this;
        }

        public Criteria andWennesdayIn(List<byte[]> values) {
            addCriterion("WENNESDAY in", values, "wennesday");
            return (Criteria) this;
        }

        public Criteria andWennesdayNotIn(List<byte[]> values) {
            addCriterion("WENNESDAY not in", values, "wennesday");
            return (Criteria) this;
        }

        public Criteria andWennesdayBetween(byte[] value1, byte[] value2) {
            addCriterion("WENNESDAY between", value1, value2, "wennesday");
            return (Criteria) this;
        }

        public Criteria andWennesdayNotBetween(byte[] value1, byte[] value2) {
            addCriterion("WENNESDAY not between", value1, value2, "wennesday");
            return (Criteria) this;
        }

        public Criteria andFirdayIsNull() {
            addCriterion("FIRDAY is null");
            return (Criteria) this;
        }

        public Criteria andFirdayIsNotNull() {
            addCriterion("FIRDAY is not null");
            return (Criteria) this;
        }

        public Criteria andFirdayEqualTo(byte[] value) {
            addCriterion("FIRDAY =", value, "firday");
            return (Criteria) this;
        }

        public Criteria andFirdayNotEqualTo(byte[] value) {
            addCriterion("FIRDAY <>", value, "firday");
            return (Criteria) this;
        }

        public Criteria andFirdayGreaterThan(byte[] value) {
            addCriterion("FIRDAY >", value, "firday");
            return (Criteria) this;
        }

        public Criteria andFirdayGreaterThanOrEqualTo(byte[] value) {
            addCriterion("FIRDAY >=", value, "firday");
            return (Criteria) this;
        }

        public Criteria andFirdayLessThan(byte[] value) {
            addCriterion("FIRDAY <", value, "firday");
            return (Criteria) this;
        }

        public Criteria andFirdayLessThanOrEqualTo(byte[] value) {
            addCriterion("FIRDAY <=", value, "firday");
            return (Criteria) this;
        }

        public Criteria andFirdayIn(List<byte[]> values) {
            addCriterion("FIRDAY in", values, "firday");
            return (Criteria) this;
        }

        public Criteria andFirdayNotIn(List<byte[]> values) {
            addCriterion("FIRDAY not in", values, "firday");
            return (Criteria) this;
        }

        public Criteria andFirdayBetween(byte[] value1, byte[] value2) {
            addCriterion("FIRDAY between", value1, value2, "firday");
            return (Criteria) this;
        }

        public Criteria andFirdayNotBetween(byte[] value1, byte[] value2) {
            addCriterion("FIRDAY not between", value1, value2, "firday");
            return (Criteria) this;
        }

        public Criteria andSaturdayIsNull() {
            addCriterion("SATURDAY is null");
            return (Criteria) this;
        }

        public Criteria andSaturdayIsNotNull() {
            addCriterion("SATURDAY is not null");
            return (Criteria) this;
        }

        public Criteria andSaturdayEqualTo(byte[] value) {
            addCriterion("SATURDAY =", value, "saturday");
            return (Criteria) this;
        }

        public Criteria andSaturdayNotEqualTo(byte[] value) {
            addCriterion("SATURDAY <>", value, "saturday");
            return (Criteria) this;
        }

        public Criteria andSaturdayGreaterThan(byte[] value) {
            addCriterion("SATURDAY >", value, "saturday");
            return (Criteria) this;
        }

        public Criteria andSaturdayGreaterThanOrEqualTo(byte[] value) {
            addCriterion("SATURDAY >=", value, "saturday");
            return (Criteria) this;
        }

        public Criteria andSaturdayLessThan(byte[] value) {
            addCriterion("SATURDAY <", value, "saturday");
            return (Criteria) this;
        }

        public Criteria andSaturdayLessThanOrEqualTo(byte[] value) {
            addCriterion("SATURDAY <=", value, "saturday");
            return (Criteria) this;
        }

        public Criteria andSaturdayIn(List<byte[]> values) {
            addCriterion("SATURDAY in", values, "saturday");
            return (Criteria) this;
        }

        public Criteria andSaturdayNotIn(List<byte[]> values) {
            addCriterion("SATURDAY not in", values, "saturday");
            return (Criteria) this;
        }

        public Criteria andSaturdayBetween(byte[] value1, byte[] value2) {
            addCriterion("SATURDAY between", value1, value2, "saturday");
            return (Criteria) this;
        }

        public Criteria andSaturdayNotBetween(byte[] value1, byte[] value2) {
            addCriterion("SATURDAY not between", value1, value2, "saturday");
            return (Criteria) this;
        }

        public Criteria andSundayIsNull() {
            addCriterion("SUNDAY is null");
            return (Criteria) this;
        }

        public Criteria andSundayIsNotNull() {
            addCriterion("SUNDAY is not null");
            return (Criteria) this;
        }

        public Criteria andSundayEqualTo(byte[] value) {
            addCriterion("SUNDAY =", value, "sunday");
            return (Criteria) this;
        }

        public Criteria andSundayNotEqualTo(byte[] value) {
            addCriterion("SUNDAY <>", value, "sunday");
            return (Criteria) this;
        }

        public Criteria andSundayGreaterThan(byte[] value) {
            addCriterion("SUNDAY >", value, "sunday");
            return (Criteria) this;
        }

        public Criteria andSundayGreaterThanOrEqualTo(byte[] value) {
            addCriterion("SUNDAY >=", value, "sunday");
            return (Criteria) this;
        }

        public Criteria andSundayLessThan(byte[] value) {
            addCriterion("SUNDAY <", value, "sunday");
            return (Criteria) this;
        }

        public Criteria andSundayLessThanOrEqualTo(byte[] value) {
            addCriterion("SUNDAY <=", value, "sunday");
            return (Criteria) this;
        }

        public Criteria andSundayIn(List<byte[]> values) {
            addCriterion("SUNDAY in", values, "sunday");
            return (Criteria) this;
        }

        public Criteria andSundayNotIn(List<byte[]> values) {
            addCriterion("SUNDAY not in", values, "sunday");
            return (Criteria) this;
        }

        public Criteria andSundayBetween(byte[] value1, byte[] value2) {
            addCriterion("SUNDAY between", value1, value2, "sunday");
            return (Criteria) this;
        }

        public Criteria andSundayNotBetween(byte[] value1, byte[] value2) {
            addCriterion("SUNDAY not between", value1, value2, "sunday");
            return (Criteria) this;
        }

        public Criteria andInspectionsystemidIsNull() {
            addCriterion("INSPECTIONSYSTEMID is null");
            return (Criteria) this;
        }

        public Criteria andInspectionsystemidIsNotNull() {
            addCriterion("INSPECTIONSYSTEMID is not null");
            return (Criteria) this;
        }

        public Criteria andInspectionsystemidEqualTo(Integer value) {
            addCriterion("INSPECTIONSYSTEMID =", value, "inspectionsystemid");
            return (Criteria) this;
        }

        public Criteria andInspectionsystemidNotEqualTo(Integer value) {
            addCriterion("INSPECTIONSYSTEMID <>", value, "inspectionsystemid");
            return (Criteria) this;
        }

        public Criteria andInspectionsystemidGreaterThan(Integer value) {
            addCriterion("INSPECTIONSYSTEMID >", value, "inspectionsystemid");
            return (Criteria) this;
        }

        public Criteria andInspectionsystemidGreaterThanOrEqualTo(Integer value) {
            addCriterion("INSPECTIONSYSTEMID >=", value, "inspectionsystemid");
            return (Criteria) this;
        }

        public Criteria andInspectionsystemidLessThan(Integer value) {
            addCriterion("INSPECTIONSYSTEMID <", value, "inspectionsystemid");
            return (Criteria) this;
        }

        public Criteria andInspectionsystemidLessThanOrEqualTo(Integer value) {
            addCriterion("INSPECTIONSYSTEMID <=", value, "inspectionsystemid");
            return (Criteria) this;
        }

        public Criteria andInspectionsystemidIn(List<Integer> values) {
            addCriterion("INSPECTIONSYSTEMID in", values, "inspectionsystemid");
            return (Criteria) this;
        }

        public Criteria andInspectionsystemidNotIn(List<Integer> values) {
            addCriterion("INSPECTIONSYSTEMID not in", values, "inspectionsystemid");
            return (Criteria) this;
        }

        public Criteria andInspectionsystemidBetween(Integer value1, Integer value2) {
            addCriterion("INSPECTIONSYSTEMID between", value1, value2, "inspectionsystemid");
            return (Criteria) this;
        }

        public Criteria andInspectionsystemidNotBetween(Integer value1, Integer value2) {
            addCriterion("INSPECTIONSYSTEMID not between", value1, value2, "inspectionsystemid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INSPECTION
     *
     * @mbg.generated do_not_delete_during_merge Fri Mar 09 16:03:32 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INSPECTION
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}