package com.james.ssm.po;

public class Memuleft {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memuleft.id
     *
     * @mbg.generated Wed Mar 28 15:28:11 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memuleft.nodeName
     *
     * @mbg.generated Wed Mar 28 15:28:11 CST 2018
     */
    private String nodename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memuleft.nodeUrl
     *
     * @mbg.generated Wed Mar 28 15:28:11 CST 2018
     */
    private String nodeurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memuleft.isleat
     *
     * @mbg.generated Wed Mar 28 15:28:11 CST 2018
     */
    private Boolean isleat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memuleft.parentId
     *
     * @mbg.generated Wed Mar 28 15:28:11 CST 2018
     */
    private Integer parentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memuleft.id
     *
     * @return the value of memuleft.id
     *
     * @mbg.generated Wed Mar 28 15:28:11 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memuleft.id
     *
     * @param id the value for memuleft.id
     *
     * @mbg.generated Wed Mar 28 15:28:11 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memuleft.nodeName
     *
     * @return the value of memuleft.nodeName
     *
     * @mbg.generated Wed Mar 28 15:28:11 CST 2018
     */
    public String getNodename() {
        return nodename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memuleft.nodeName
     *
     * @param nodename the value for memuleft.nodeName
     *
     * @mbg.generated Wed Mar 28 15:28:11 CST 2018
     */
    public void setNodename(String nodename) {
        this.nodename = nodename == null ? null : nodename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memuleft.nodeUrl
     *
     * @return the value of memuleft.nodeUrl
     *
     * @mbg.generated Wed Mar 28 15:28:11 CST 2018
     */
    public String getNodeurl() {
        return nodeurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memuleft.nodeUrl
     *
     * @param nodeurl the value for memuleft.nodeUrl
     *
     * @mbg.generated Wed Mar 28 15:28:11 CST 2018
     */
    public void setNodeurl(String nodeurl) {
        this.nodeurl = nodeurl == null ? null : nodeurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memuleft.isleat
     *
     * @return the value of memuleft.isleat
     *
     * @mbg.generated Wed Mar 28 15:28:11 CST 2018
     */
    public Boolean getIsleat() {
        return isleat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memuleft.isleat
     *
     * @param isleat the value for memuleft.isleat
     *
     * @mbg.generated Wed Mar 28 15:28:11 CST 2018
     */
    public void setIsleat(Boolean isleat) {
        this.isleat = isleat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memuleft.parentId
     *
     * @return the value of memuleft.parentId
     *
     * @mbg.generated Wed Mar 28 15:28:11 CST 2018
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memuleft.parentId
     *
     * @param parentid the value for memuleft.parentId
     *
     * @mbg.generated Wed Mar 28 15:28:11 CST 2018
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }
}