package com.james.ssm.po;

public class Permissions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.id
     *
     * @mbg.generated Wed Mar 28 15:11:08 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.permissionsname
     *
     * @mbg.generated Wed Mar 28 15:11:08 CST 2018
     */
    private String permissionsname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.id
     *
     * @return the value of permissions.id
     *
     * @mbg.generated Wed Mar 28 15:11:08 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.id
     *
     * @param id the value for permissions.id
     *
     * @mbg.generated Wed Mar 28 15:11:08 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.permissionsname
     *
     * @return the value of permissions.permissionsname
     *
     * @mbg.generated Wed Mar 28 15:11:08 CST 2018
     */
    public String getPermissionsname() {
        return permissionsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.permissionsname
     *
     * @param permissionsname the value for permissions.permissionsname
     *
     * @mbg.generated Wed Mar 28 15:11:08 CST 2018
     */
    public void setPermissionsname(String permissionsname) {
        this.permissionsname = permissionsname == null ? null : permissionsname.trim();
    }
}