package com.james.ssm.po;

import java.util.Date;

public class Recondition {

    private Integer id;

    private String nu;

    private String rname;

    private Date createtime;

    private Date rstarttime;

    private Date rendtime;

    private byte[] confirm;

    private Integer createman;

    private Integer watchman;

    private Integer auditman;

    private String rtype;

    private String rleve;

    private String rcontext;


    private String scope;

    private byte[] sgccconfirm;

    private byte[] dpconfirm;

    private byte[] sgccsdconfirm;

    private byte[] rwindow;

    private byte[] isdown;


    private byte[] isruntypechange;


    private String risk;


    private String timecode;

    private byte[] sgcccsconfirm;




    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RECONDITION.ID
     *
     * @param id the value for RECONDITION.ID
     *
*/
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RECONDITION.NU
     *
     * @return the value of RECONDITION.NU
     *
*/
    public String getNu() {
        return nu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RECONDITION.NU
     *
     * @param nu the value for RECONDITION.NU
     *
*/
    public void setNu(String nu) {
        this.nu = nu == null ? null : nu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RECONDITION.RNAME
     *
     * @return the value of RECONDITION.RNAME
     *
*/
    public String getRname() {
        return rname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RECONDITION.RNAME
     *
     * @param rname the value for RECONDITION.RNAME
     *
*/
    public void setRname(String rname) {
        this.rname = rname == null ? null : rname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RECONDITION.CREATETIME
     *
     * @return the value of RECONDITION.CREATETIME
     *
*/
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RECONDITION.CREATETIME
     *
     * @param createtime the value for RECONDITION.CREATETIME
     *
*/
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RECONDITION.RSTARTTIME
     *
     * @return the value of RECONDITION.RSTARTTIME
     *
*/
    public Date getRstarttime() {
        return rstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RECONDITION.RSTARTTIME
     *
     * @param rstarttime the value for RECONDITION.RSTARTTIME
     *
*/
    public void setRstarttime(Date rstarttime) {
        this.rstarttime = rstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RECONDITION.RENDTIME
     *
     * @return the value of RECONDITION.RENDTIME
     *
*/
    public Date getRendtime() {
        return rendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RECONDITION.RENDTIME
     *
     * @param rendtime the value for RECONDITION.RENDTIME
     *
*/
    public void setRendtime(Date rendtime) {
        this.rendtime = rendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RECONDITION.CONFIRM
     *
     * @return the value of RECONDITION.CONFIRM
     *
*/
    public byte[] getConfirm() {
        return confirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RECONDITION.CONFIRM
     *
     * @param confirm the value for RECONDITION.CONFIRM
     *
*/
    public void setConfirm(byte[] confirm) {
        this.confirm = confirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RECONDITION.CREATEMAN
     *
     * @return the value of RECONDITION.CREATEMAN
     *
*/
    public Integer getCreateman() {
        return createman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RECONDITION.CREATEMAN
     *
     * @param createman the value for RECONDITION.CREATEMAN
     *
*/
    public void setCreateman(Integer createman) {
        this.createman = createman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RECONDITION.WATCHMAN
     *
     * @return the value of RECONDITION.WATCHMAN
     *
*/
    public Integer getWatchman() {
        return watchman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RECONDITION.WATCHMAN
     *
     * @param watchman the value for RECONDITION.WATCHMAN
     *
*/
    public void setWatchman(Integer watchman) {
        this.watchman = watchman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RECONDITION.AUDITMAN
     *
     * @return the value of RECONDITION.AUDITMAN
     *
*/
    public Integer getAuditman() {
        return auditman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RECONDITION.AUDITMAN
     *
     * @param auditman the value for RECONDITION.AUDITMAN
     *
*/
    public void setAuditman(Integer auditman) {
        this.auditman = auditman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RECONDITION.RTYPE
     *
     * @return the value of RECONDITION.RTYPE
     *
*/
    public String getRtype() {
        return rtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RECONDITION.RTYPE
     *
     * @param rtype the value for RECONDITION.RTYPE
     *
*/
    public void setRtype(String rtype) {
        this.rtype = rtype == null ? null : rtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RECONDITION.RLEVE
     *
     * @return the value of RECONDITION.RLEVE
     *
*/
    public String getRleve() {
        return rleve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RECONDITION.RLEVE
     *
     * @param rleve the value for RECONDITION.RLEVE
     *
*/
    public void setRleve(String rleve) {
        this.rleve = rleve == null ? null : rleve.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RECONDITION.RCONTEXT
     *
     * @return the value of RECONDITION.RCONTEXT
     *
*/
    public String getRcontext() {
        return rcontext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RECONDITION.RCONTEXT
     *
     * @param rcontext the value for RECONDITION.RCONTEXT
     *
*/
    public void setRcontext(String rcontext) {
        this.rcontext = rcontext == null ? null : rcontext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RECONDITION.SCOPE
     *
     * @return the value of RECONDITION.SCOPE
     *
*/
    public String getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RECONDITION.SCOPE
     *
     * @param scope the value for RECONDITION.SCOPE
     *
*/
    public void setScope(String scope) {
        this.scope = scope == null ? null : scope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RECONDITION.SGCCCONFIRM
     *
     * @return the value of RECONDITION.SGCCCONFIRM
     *
*/
    public byte[] getSgccconfirm() {
        return sgccconfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RECONDITION.SGCCCONFIRM
     *
     * @param sgccconfirm the value for RECONDITION.SGCCCONFIRM
     *
*/
    public void setSgccconfirm(byte[] sgccconfirm) {
        this.sgccconfirm = sgccconfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RECONDITION.DPCONFIRM
     *
     * @return the value of RECONDITION.DPCONFIRM
     *
*/
    public byte[] getDpconfirm() {
        return dpconfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RECONDITION.DPCONFIRM
     *
     * @param dpconfirm the value for RECONDITION.DPCONFIRM
     *
*/
    public void setDpconfirm(byte[] dpconfirm) {
        this.dpconfirm = dpconfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RECONDITION.SGCCSDCONFIRM
     *
     * @return the value of RECONDITION.SGCCSDCONFIRM
     *
*/
    public byte[] getSgccsdconfirm() {
        return sgccsdconfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RECONDITION.SGCCSDCONFIRM
     *
     * @param sgccsdconfirm the value for RECONDITION.SGCCSDCONFIRM
     *
*/
    public void setSgccsdconfirm(byte[] sgccsdconfirm) {
        this.sgccsdconfirm = sgccsdconfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RECONDITION.RWINDOW
     *
     * @return the value of RECONDITION.RWINDOW
     *
*/
    public byte[] getRwindow() {
        return rwindow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RECONDITION.RWINDOW
     *
     * @param rwindow the value for RECONDITION.RWINDOW
     *
*/
    public void setRwindow(byte[] rwindow) {
        this.rwindow = rwindow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RECONDITION.ISDOWN
     *
     * @return the value of RECONDITION.ISDOWN
     *
*/
    public byte[] getIsdown() {
        return isdown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RECONDITION.ISDOWN
     *
     * @param isdown the value for RECONDITION.ISDOWN
     *
*/
    public void setIsdown(byte[] isdown) {
        this.isdown = isdown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RECONDITION.ISRUNTYPECHANGE
     *
     * @return the value of RECONDITION.ISRUNTYPECHANGE
     *
*/
    public byte[] getIsruntypechange() {
        return isruntypechange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RECONDITION.ISRUNTYPECHANGE
     *
     * @param isruntypechange the value for RECONDITION.ISRUNTYPECHANGE
     *
*/
    public void setIsruntypechange(byte[] isruntypechange) {
        this.isruntypechange = isruntypechange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RECONDITION.RISK
     *
     * @return the value of RECONDITION.RISK
     *
*/
    public String getRisk() {
        return risk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RECONDITION.RISK
     *
     * @param risk the value for RECONDITION.RISK
     *
*/
    public void setRisk(String risk) {
        this.risk = risk == null ? null : risk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RECONDITION.TIMECODE
     *
     * @return the value of RECONDITION.TIMECODE
     *
*/
    public String getTimecode() {
        return timecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RECONDITION.TIMECODE
     *
     * @param timecode the value for RECONDITION.TIMECODE
     *
*/
    public void setTimecode(String timecode) {
        this.timecode = timecode == null ? null : timecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RECONDITION.SGCCCSCONFIRM
     *
     * @return the value of RECONDITION.SGCCCSCONFIRM
     *
*/
    public byte[] getSgcccsconfirm() {
        return sgcccsconfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RECONDITION.SGCCCSCONFIRM
     *
     * @param sgcccsconfirm the value for RECONDITION.SGCCCSCONFIRM
     *
*/
    public void setSgcccsconfirm(byte[] sgcccsconfirm) {
        this.sgcccsconfirm = sgcccsconfirm;
    }
}