package com.james.ssm.po;

public class Rolspermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolspermission.id
     *
     * @mbg.generated Wed Mar 28 15:11:08 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolspermission.rolsid
     *
     * @mbg.generated Wed Mar 28 15:11:08 CST 2018
     */
    private Integer rolsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolspermission.permissionsid
     *
     * @mbg.generated Wed Mar 28 15:11:08 CST 2018
     */
    private Integer permissionsid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolspermission.id
     *
     * @return the value of rolspermission.id
     *
     * @mbg.generated Wed Mar 28 15:11:08 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolspermission.id
     *
     * @param id the value for rolspermission.id
     *
     * @mbg.generated Wed Mar 28 15:11:08 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolspermission.rolsid
     *
     * @return the value of rolspermission.rolsid
     *
     * @mbg.generated Wed Mar 28 15:11:08 CST 2018
     */
    public Integer getRolsid() {
        return rolsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolspermission.rolsid
     *
     * @param rolsid the value for rolspermission.rolsid
     *
     * @mbg.generated Wed Mar 28 15:11:08 CST 2018
     */
    public void setRolsid(Integer rolsid) {
        this.rolsid = rolsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolspermission.permissionsid
     *
     * @return the value of rolspermission.permissionsid
     *
     * @mbg.generated Wed Mar 28 15:11:08 CST 2018
     */
    public Integer getPermissionsid() {
        return permissionsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolspermission.permissionsid
     *
     * @param permissionsid the value for rolspermission.permissionsid
     *
     * @mbg.generated Wed Mar 28 15:11:08 CST 2018
     */
    public void setPermissionsid(Integer permissionsid) {
        this.permissionsid = permissionsid;
    }
}