package com.james.ssm.po;

public class Rols {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rols.id
     *
     * @mbg.generated Wed Mar 28 15:11:08 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rols.rolsname
     *
     * @mbg.generated Wed Mar 28 15:11:08 CST 2018
     */
    private String rolsname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rols.id
     *
     * @return the value of rols.id
     *
     * @mbg.generated Wed Mar 28 15:11:08 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rols.id
     *
     * @param id the value for rols.id
     *
     * @mbg.generated Wed Mar 28 15:11:08 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rols.rolsname
     *
     * @return the value of rols.rolsname
     *
     * @mbg.generated Wed Mar 28 15:11:08 CST 2018
     */
    public String getRolsname() {
        return rolsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rols.rolsname
     *
     * @param rolsname the value for rols.rolsname
     *
     * @mbg.generated Wed Mar 28 15:11:08 CST 2018
     */
    public void setRolsname(String rolsname) {
        this.rolsname = rolsname == null ? null : rolsname.trim();
    }
}