package com.james.ssm.po;

public class Systeminfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEMINFO.ID
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEMINFO.SYSTEMNAME
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    private String systemname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEMINFO.DEVOLOOPMENTTYPE
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    private String devoloopmenttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEMINFO.SYSTEMMAN
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    private Integer systemman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEMINFO.SECENDMAN
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    private Integer secendman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEMINFO.SYSTEMINTRO
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    private String systemintro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEMINFO.SYSTEMTYPE
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    private String systemtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEMINFO.SYSTEMLEVEL
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    private String systemlevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEMINFO.SYSTEMSUPPORTMAN1
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    private Integer systemsupportman1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEMINFO.SYSTEMSUPPORTMAN2
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    private Integer systemsupportman2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEMINFO.SYSTEMSUPPORTMAN3
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    private Integer systemsupportman3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEMINFO.SYSTEMSUPPORTMAN4
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    private Integer systemsupportman4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEMINFO.SYSTEMSUPPORTMAN5
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    private Integer systemsupportman5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEMINFO.SYSTEMSUPPORTMAN6
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    private Integer systemsupportman6;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEMINFO.ID
     *
     * @return the value of SYSTEMINFO.ID
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEMINFO.ID
     *
     * @param id the value for SYSTEMINFO.ID
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEMINFO.SYSTEMNAME
     *
     * @return the value of SYSTEMINFO.SYSTEMNAME
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public String getSystemname() {
        return systemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEMINFO.SYSTEMNAME
     *
     * @param systemname the value for SYSTEMINFO.SYSTEMNAME
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setSystemname(String systemname) {
        this.systemname = systemname == null ? null : systemname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEMINFO.DEVOLOOPMENTTYPE
     *
     * @return the value of SYSTEMINFO.DEVOLOOPMENTTYPE
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public String getDevoloopmenttype() {
        return devoloopmenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEMINFO.DEVOLOOPMENTTYPE
     *
     * @param devoloopmenttype the value for SYSTEMINFO.DEVOLOOPMENTTYPE
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setDevoloopmenttype(String devoloopmenttype) {
        this.devoloopmenttype = devoloopmenttype == null ? null : devoloopmenttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEMINFO.SYSTEMMAN
     *
     * @return the value of SYSTEMINFO.SYSTEMMAN
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public Integer getSystemman() {
        return systemman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEMINFO.SYSTEMMAN
     *
     * @param systemman the value for SYSTEMINFO.SYSTEMMAN
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setSystemman(Integer systemman) {
        this.systemman = systemman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEMINFO.SECENDMAN
     *
     * @return the value of SYSTEMINFO.SECENDMAN
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public Integer getSecendman() {
        return secendman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEMINFO.SECENDMAN
     *
     * @param secendman the value for SYSTEMINFO.SECENDMAN
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setSecendman(Integer secendman) {
        this.secendman = secendman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEMINFO.SYSTEMINTRO
     *
     * @return the value of SYSTEMINFO.SYSTEMINTRO
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public String getSystemintro() {
        return systemintro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEMINFO.SYSTEMINTRO
     *
     * @param systemintro the value for SYSTEMINFO.SYSTEMINTRO
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setSystemintro(String systemintro) {
        this.systemintro = systemintro == null ? null : systemintro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEMINFO.SYSTEMTYPE
     *
     * @return the value of SYSTEMINFO.SYSTEMTYPE
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public String getSystemtype() {
        return systemtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEMINFO.SYSTEMTYPE
     *
     * @param systemtype the value for SYSTEMINFO.SYSTEMTYPE
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setSystemtype(String systemtype) {
        this.systemtype = systemtype == null ? null : systemtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEMINFO.SYSTEMLEVEL
     *
     * @return the value of SYSTEMINFO.SYSTEMLEVEL
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public String getSystemlevel() {
        return systemlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEMINFO.SYSTEMLEVEL
     *
     * @param systemlevel the value for SYSTEMINFO.SYSTEMLEVEL
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setSystemlevel(String systemlevel) {
        this.systemlevel = systemlevel == null ? null : systemlevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEMINFO.SYSTEMSUPPORTMAN1
     *
     * @return the value of SYSTEMINFO.SYSTEMSUPPORTMAN1
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public Integer getSystemsupportman1() {
        return systemsupportman1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEMINFO.SYSTEMSUPPORTMAN1
     *
     * @param systemsupportman1 the value for SYSTEMINFO.SYSTEMSUPPORTMAN1
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setSystemsupportman1(Integer systemsupportman1) {
        this.systemsupportman1 = systemsupportman1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEMINFO.SYSTEMSUPPORTMAN2
     *
     * @return the value of SYSTEMINFO.SYSTEMSUPPORTMAN2
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public Integer getSystemsupportman2() {
        return systemsupportman2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEMINFO.SYSTEMSUPPORTMAN2
     *
     * @param systemsupportman2 the value for SYSTEMINFO.SYSTEMSUPPORTMAN2
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setSystemsupportman2(Integer systemsupportman2) {
        this.systemsupportman2 = systemsupportman2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEMINFO.SYSTEMSUPPORTMAN3
     *
     * @return the value of SYSTEMINFO.SYSTEMSUPPORTMAN3
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public Integer getSystemsupportman3() {
        return systemsupportman3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEMINFO.SYSTEMSUPPORTMAN3
     *
     * @param systemsupportman3 the value for SYSTEMINFO.SYSTEMSUPPORTMAN3
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setSystemsupportman3(Integer systemsupportman3) {
        this.systemsupportman3 = systemsupportman3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEMINFO.SYSTEMSUPPORTMAN4
     *
     * @return the value of SYSTEMINFO.SYSTEMSUPPORTMAN4
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public Integer getSystemsupportman4() {
        return systemsupportman4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEMINFO.SYSTEMSUPPORTMAN4
     *
     * @param systemsupportman4 the value for SYSTEMINFO.SYSTEMSUPPORTMAN4
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setSystemsupportman4(Integer systemsupportman4) {
        this.systemsupportman4 = systemsupportman4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEMINFO.SYSTEMSUPPORTMAN5
     *
     * @return the value of SYSTEMINFO.SYSTEMSUPPORTMAN5
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public Integer getSystemsupportman5() {
        return systemsupportman5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEMINFO.SYSTEMSUPPORTMAN5
     *
     * @param systemsupportman5 the value for SYSTEMINFO.SYSTEMSUPPORTMAN5
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setSystemsupportman5(Integer systemsupportman5) {
        this.systemsupportman5 = systemsupportman5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEMINFO.SYSTEMSUPPORTMAN6
     *
     * @return the value of SYSTEMINFO.SYSTEMSUPPORTMAN6
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public Integer getSystemsupportman6() {
        return systemsupportman6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEMINFO.SYSTEMSUPPORTMAN6
     *
     * @param systemsupportman6 the value for SYSTEMINFO.SYSTEMSUPPORTMAN6
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setSystemsupportman6(Integer systemsupportman6) {
        this.systemsupportman6 = systemsupportman6;
    }
}