package com.james.ssm.po;

import java.util.ArrayList;
import java.util.List;

public class SysteminfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSTEMINFO
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSTEMINFO
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSTEMINFO
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEMINFO
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public SysteminfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEMINFO
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEMINFO
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEMINFO
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEMINFO
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEMINFO
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEMINFO
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEMINFO
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEMINFO
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEMINFO
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEMINFO
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYSTEMINFO
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSystemnameIsNull() {
            addCriterion("SYSTEMNAME is null");
            return (Criteria) this;
        }

        public Criteria andSystemnameIsNotNull() {
            addCriterion("SYSTEMNAME is not null");
            return (Criteria) this;
        }

        public Criteria andSystemnameEqualTo(String value) {
            addCriterion("SYSTEMNAME =", value, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameNotEqualTo(String value) {
            addCriterion("SYSTEMNAME <>", value, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameGreaterThan(String value) {
            addCriterion("SYSTEMNAME >", value, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameGreaterThanOrEqualTo(String value) {
            addCriterion("SYSTEMNAME >=", value, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameLessThan(String value) {
            addCriterion("SYSTEMNAME <", value, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameLessThanOrEqualTo(String value) {
            addCriterion("SYSTEMNAME <=", value, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameLike(String value) {
            addCriterion("SYSTEMNAME like", value, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameNotLike(String value) {
            addCriterion("SYSTEMNAME not like", value, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameIn(List<String> values) {
            addCriterion("SYSTEMNAME in", values, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameNotIn(List<String> values) {
            addCriterion("SYSTEMNAME not in", values, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameBetween(String value1, String value2) {
            addCriterion("SYSTEMNAME between", value1, value2, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameNotBetween(String value1, String value2) {
            addCriterion("SYSTEMNAME not between", value1, value2, "systemname");
            return (Criteria) this;
        }

        public Criteria andDevoloopmenttypeIsNull() {
            addCriterion("DEVOLOOPMENTTYPE is null");
            return (Criteria) this;
        }

        public Criteria andDevoloopmenttypeIsNotNull() {
            addCriterion("DEVOLOOPMENTTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andDevoloopmenttypeEqualTo(String value) {
            addCriterion("DEVOLOOPMENTTYPE =", value, "devoloopmenttype");
            return (Criteria) this;
        }

        public Criteria andDevoloopmenttypeNotEqualTo(String value) {
            addCriterion("DEVOLOOPMENTTYPE <>", value, "devoloopmenttype");
            return (Criteria) this;
        }

        public Criteria andDevoloopmenttypeGreaterThan(String value) {
            addCriterion("DEVOLOOPMENTTYPE >", value, "devoloopmenttype");
            return (Criteria) this;
        }

        public Criteria andDevoloopmenttypeGreaterThanOrEqualTo(String value) {
            addCriterion("DEVOLOOPMENTTYPE >=", value, "devoloopmenttype");
            return (Criteria) this;
        }

        public Criteria andDevoloopmenttypeLessThan(String value) {
            addCriterion("DEVOLOOPMENTTYPE <", value, "devoloopmenttype");
            return (Criteria) this;
        }

        public Criteria andDevoloopmenttypeLessThanOrEqualTo(String value) {
            addCriterion("DEVOLOOPMENTTYPE <=", value, "devoloopmenttype");
            return (Criteria) this;
        }

        public Criteria andDevoloopmenttypeLike(String value) {
            addCriterion("DEVOLOOPMENTTYPE like", value, "devoloopmenttype");
            return (Criteria) this;
        }

        public Criteria andDevoloopmenttypeNotLike(String value) {
            addCriterion("DEVOLOOPMENTTYPE not like", value, "devoloopmenttype");
            return (Criteria) this;
        }

        public Criteria andDevoloopmenttypeIn(List<String> values) {
            addCriterion("DEVOLOOPMENTTYPE in", values, "devoloopmenttype");
            return (Criteria) this;
        }

        public Criteria andDevoloopmenttypeNotIn(List<String> values) {
            addCriterion("DEVOLOOPMENTTYPE not in", values, "devoloopmenttype");
            return (Criteria) this;
        }

        public Criteria andDevoloopmenttypeBetween(String value1, String value2) {
            addCriterion("DEVOLOOPMENTTYPE between", value1, value2, "devoloopmenttype");
            return (Criteria) this;
        }

        public Criteria andDevoloopmenttypeNotBetween(String value1, String value2) {
            addCriterion("DEVOLOOPMENTTYPE not between", value1, value2, "devoloopmenttype");
            return (Criteria) this;
        }

        public Criteria andSystemmanIsNull() {
            addCriterion("SYSTEMMAN is null");
            return (Criteria) this;
        }

        public Criteria andSystemmanIsNotNull() {
            addCriterion("SYSTEMMAN is not null");
            return (Criteria) this;
        }

        public Criteria andSystemmanEqualTo(Integer value) {
            addCriterion("SYSTEMMAN =", value, "systemman");
            return (Criteria) this;
        }

        public Criteria andSystemmanNotEqualTo(Integer value) {
            addCriterion("SYSTEMMAN <>", value, "systemman");
            return (Criteria) this;
        }

        public Criteria andSystemmanGreaterThan(Integer value) {
            addCriterion("SYSTEMMAN >", value, "systemman");
            return (Criteria) this;
        }

        public Criteria andSystemmanGreaterThanOrEqualTo(Integer value) {
            addCriterion("SYSTEMMAN >=", value, "systemman");
            return (Criteria) this;
        }

        public Criteria andSystemmanLessThan(Integer value) {
            addCriterion("SYSTEMMAN <", value, "systemman");
            return (Criteria) this;
        }

        public Criteria andSystemmanLessThanOrEqualTo(Integer value) {
            addCriterion("SYSTEMMAN <=", value, "systemman");
            return (Criteria) this;
        }

        public Criteria andSystemmanIn(List<Integer> values) {
            addCriterion("SYSTEMMAN in", values, "systemman");
            return (Criteria) this;
        }

        public Criteria andSystemmanNotIn(List<Integer> values) {
            addCriterion("SYSTEMMAN not in", values, "systemman");
            return (Criteria) this;
        }

        public Criteria andSystemmanBetween(Integer value1, Integer value2) {
            addCriterion("SYSTEMMAN between", value1, value2, "systemman");
            return (Criteria) this;
        }

        public Criteria andSystemmanNotBetween(Integer value1, Integer value2) {
            addCriterion("SYSTEMMAN not between", value1, value2, "systemman");
            return (Criteria) this;
        }

        public Criteria andSecendmanIsNull() {
            addCriterion("SECENDMAN is null");
            return (Criteria) this;
        }

        public Criteria andSecendmanIsNotNull() {
            addCriterion("SECENDMAN is not null");
            return (Criteria) this;
        }

        public Criteria andSecendmanEqualTo(Integer value) {
            addCriterion("SECENDMAN =", value, "secendman");
            return (Criteria) this;
        }

        public Criteria andSecendmanNotEqualTo(Integer value) {
            addCriterion("SECENDMAN <>", value, "secendman");
            return (Criteria) this;
        }

        public Criteria andSecendmanGreaterThan(Integer value) {
            addCriterion("SECENDMAN >", value, "secendman");
            return (Criteria) this;
        }

        public Criteria andSecendmanGreaterThanOrEqualTo(Integer value) {
            addCriterion("SECENDMAN >=", value, "secendman");
            return (Criteria) this;
        }

        public Criteria andSecendmanLessThan(Integer value) {
            addCriterion("SECENDMAN <", value, "secendman");
            return (Criteria) this;
        }

        public Criteria andSecendmanLessThanOrEqualTo(Integer value) {
            addCriterion("SECENDMAN <=", value, "secendman");
            return (Criteria) this;
        }

        public Criteria andSecendmanIn(List<Integer> values) {
            addCriterion("SECENDMAN in", values, "secendman");
            return (Criteria) this;
        }

        public Criteria andSecendmanNotIn(List<Integer> values) {
            addCriterion("SECENDMAN not in", values, "secendman");
            return (Criteria) this;
        }

        public Criteria andSecendmanBetween(Integer value1, Integer value2) {
            addCriterion("SECENDMAN between", value1, value2, "secendman");
            return (Criteria) this;
        }

        public Criteria andSecendmanNotBetween(Integer value1, Integer value2) {
            addCriterion("SECENDMAN not between", value1, value2, "secendman");
            return (Criteria) this;
        }

        public Criteria andSystemintroIsNull() {
            addCriterion("SYSTEMINTRO is null");
            return (Criteria) this;
        }

        public Criteria andSystemintroIsNotNull() {
            addCriterion("SYSTEMINTRO is not null");
            return (Criteria) this;
        }

        public Criteria andSystemintroEqualTo(String value) {
            addCriterion("SYSTEMINTRO =", value, "systemintro");
            return (Criteria) this;
        }

        public Criteria andSystemintroNotEqualTo(String value) {
            addCriterion("SYSTEMINTRO <>", value, "systemintro");
            return (Criteria) this;
        }

        public Criteria andSystemintroGreaterThan(String value) {
            addCriterion("SYSTEMINTRO >", value, "systemintro");
            return (Criteria) this;
        }

        public Criteria andSystemintroGreaterThanOrEqualTo(String value) {
            addCriterion("SYSTEMINTRO >=", value, "systemintro");
            return (Criteria) this;
        }

        public Criteria andSystemintroLessThan(String value) {
            addCriterion("SYSTEMINTRO <", value, "systemintro");
            return (Criteria) this;
        }

        public Criteria andSystemintroLessThanOrEqualTo(String value) {
            addCriterion("SYSTEMINTRO <=", value, "systemintro");
            return (Criteria) this;
        }

        public Criteria andSystemintroLike(String value) {
            addCriterion("SYSTEMINTRO like", value, "systemintro");
            return (Criteria) this;
        }

        public Criteria andSystemintroNotLike(String value) {
            addCriterion("SYSTEMINTRO not like", value, "systemintro");
            return (Criteria) this;
        }

        public Criteria andSystemintroIn(List<String> values) {
            addCriterion("SYSTEMINTRO in", values, "systemintro");
            return (Criteria) this;
        }

        public Criteria andSystemintroNotIn(List<String> values) {
            addCriterion("SYSTEMINTRO not in", values, "systemintro");
            return (Criteria) this;
        }

        public Criteria andSystemintroBetween(String value1, String value2) {
            addCriterion("SYSTEMINTRO between", value1, value2, "systemintro");
            return (Criteria) this;
        }

        public Criteria andSystemintroNotBetween(String value1, String value2) {
            addCriterion("SYSTEMINTRO not between", value1, value2, "systemintro");
            return (Criteria) this;
        }

        public Criteria andSystemtypeIsNull() {
            addCriterion("SYSTEMTYPE is null");
            return (Criteria) this;
        }

        public Criteria andSystemtypeIsNotNull() {
            addCriterion("SYSTEMTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSystemtypeEqualTo(String value) {
            addCriterion("SYSTEMTYPE =", value, "systemtype");
            return (Criteria) this;
        }

        public Criteria andSystemtypeNotEqualTo(String value) {
            addCriterion("SYSTEMTYPE <>", value, "systemtype");
            return (Criteria) this;
        }

        public Criteria andSystemtypeGreaterThan(String value) {
            addCriterion("SYSTEMTYPE >", value, "systemtype");
            return (Criteria) this;
        }

        public Criteria andSystemtypeGreaterThanOrEqualTo(String value) {
            addCriterion("SYSTEMTYPE >=", value, "systemtype");
            return (Criteria) this;
        }

        public Criteria andSystemtypeLessThan(String value) {
            addCriterion("SYSTEMTYPE <", value, "systemtype");
            return (Criteria) this;
        }

        public Criteria andSystemtypeLessThanOrEqualTo(String value) {
            addCriterion("SYSTEMTYPE <=", value, "systemtype");
            return (Criteria) this;
        }

        public Criteria andSystemtypeLike(String value) {
            addCriterion("SYSTEMTYPE like", value, "systemtype");
            return (Criteria) this;
        }

        public Criteria andSystemtypeNotLike(String value) {
            addCriterion("SYSTEMTYPE not like", value, "systemtype");
            return (Criteria) this;
        }

        public Criteria andSystemtypeIn(List<String> values) {
            addCriterion("SYSTEMTYPE in", values, "systemtype");
            return (Criteria) this;
        }

        public Criteria andSystemtypeNotIn(List<String> values) {
            addCriterion("SYSTEMTYPE not in", values, "systemtype");
            return (Criteria) this;
        }

        public Criteria andSystemtypeBetween(String value1, String value2) {
            addCriterion("SYSTEMTYPE between", value1, value2, "systemtype");
            return (Criteria) this;
        }

        public Criteria andSystemtypeNotBetween(String value1, String value2) {
            addCriterion("SYSTEMTYPE not between", value1, value2, "systemtype");
            return (Criteria) this;
        }

        public Criteria andSystemlevelIsNull() {
            addCriterion("SYSTEMLEVEL is null");
            return (Criteria) this;
        }

        public Criteria andSystemlevelIsNotNull() {
            addCriterion("SYSTEMLEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andSystemlevelEqualTo(String value) {
            addCriterion("SYSTEMLEVEL =", value, "systemlevel");
            return (Criteria) this;
        }

        public Criteria andSystemlevelNotEqualTo(String value) {
            addCriterion("SYSTEMLEVEL <>", value, "systemlevel");
            return (Criteria) this;
        }

        public Criteria andSystemlevelGreaterThan(String value) {
            addCriterion("SYSTEMLEVEL >", value, "systemlevel");
            return (Criteria) this;
        }

        public Criteria andSystemlevelGreaterThanOrEqualTo(String value) {
            addCriterion("SYSTEMLEVEL >=", value, "systemlevel");
            return (Criteria) this;
        }

        public Criteria andSystemlevelLessThan(String value) {
            addCriterion("SYSTEMLEVEL <", value, "systemlevel");
            return (Criteria) this;
        }

        public Criteria andSystemlevelLessThanOrEqualTo(String value) {
            addCriterion("SYSTEMLEVEL <=", value, "systemlevel");
            return (Criteria) this;
        }

        public Criteria andSystemlevelLike(String value) {
            addCriterion("SYSTEMLEVEL like", value, "systemlevel");
            return (Criteria) this;
        }

        public Criteria andSystemlevelNotLike(String value) {
            addCriterion("SYSTEMLEVEL not like", value, "systemlevel");
            return (Criteria) this;
        }

        public Criteria andSystemlevelIn(List<String> values) {
            addCriterion("SYSTEMLEVEL in", values, "systemlevel");
            return (Criteria) this;
        }

        public Criteria andSystemlevelNotIn(List<String> values) {
            addCriterion("SYSTEMLEVEL not in", values, "systemlevel");
            return (Criteria) this;
        }

        public Criteria andSystemlevelBetween(String value1, String value2) {
            addCriterion("SYSTEMLEVEL between", value1, value2, "systemlevel");
            return (Criteria) this;
        }

        public Criteria andSystemlevelNotBetween(String value1, String value2) {
            addCriterion("SYSTEMLEVEL not between", value1, value2, "systemlevel");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman1IsNull() {
            addCriterion("SYSTEMSUPPORTMAN1 is null");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman1IsNotNull() {
            addCriterion("SYSTEMSUPPORTMAN1 is not null");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman1EqualTo(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN1 =", value, "systemsupportman1");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman1NotEqualTo(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN1 <>", value, "systemsupportman1");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman1GreaterThan(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN1 >", value, "systemsupportman1");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman1GreaterThanOrEqualTo(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN1 >=", value, "systemsupportman1");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman1LessThan(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN1 <", value, "systemsupportman1");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman1LessThanOrEqualTo(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN1 <=", value, "systemsupportman1");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman1In(List<Integer> values) {
            addCriterion("SYSTEMSUPPORTMAN1 in", values, "systemsupportman1");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman1NotIn(List<Integer> values) {
            addCriterion("SYSTEMSUPPORTMAN1 not in", values, "systemsupportman1");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman1Between(Integer value1, Integer value2) {
            addCriterion("SYSTEMSUPPORTMAN1 between", value1, value2, "systemsupportman1");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman1NotBetween(Integer value1, Integer value2) {
            addCriterion("SYSTEMSUPPORTMAN1 not between", value1, value2, "systemsupportman1");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman2IsNull() {
            addCriterion("SYSTEMSUPPORTMAN2 is null");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman2IsNotNull() {
            addCriterion("SYSTEMSUPPORTMAN2 is not null");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman2EqualTo(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN2 =", value, "systemsupportman2");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman2NotEqualTo(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN2 <>", value, "systemsupportman2");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman2GreaterThan(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN2 >", value, "systemsupportman2");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman2GreaterThanOrEqualTo(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN2 >=", value, "systemsupportman2");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman2LessThan(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN2 <", value, "systemsupportman2");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman2LessThanOrEqualTo(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN2 <=", value, "systemsupportman2");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman2In(List<Integer> values) {
            addCriterion("SYSTEMSUPPORTMAN2 in", values, "systemsupportman2");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman2NotIn(List<Integer> values) {
            addCriterion("SYSTEMSUPPORTMAN2 not in", values, "systemsupportman2");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman2Between(Integer value1, Integer value2) {
            addCriterion("SYSTEMSUPPORTMAN2 between", value1, value2, "systemsupportman2");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman2NotBetween(Integer value1, Integer value2) {
            addCriterion("SYSTEMSUPPORTMAN2 not between", value1, value2, "systemsupportman2");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman3IsNull() {
            addCriterion("SYSTEMSUPPORTMAN3 is null");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman3IsNotNull() {
            addCriterion("SYSTEMSUPPORTMAN3 is not null");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman3EqualTo(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN3 =", value, "systemsupportman3");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman3NotEqualTo(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN3 <>", value, "systemsupportman3");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman3GreaterThan(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN3 >", value, "systemsupportman3");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman3GreaterThanOrEqualTo(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN3 >=", value, "systemsupportman3");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman3LessThan(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN3 <", value, "systemsupportman3");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman3LessThanOrEqualTo(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN3 <=", value, "systemsupportman3");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman3In(List<Integer> values) {
            addCriterion("SYSTEMSUPPORTMAN3 in", values, "systemsupportman3");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman3NotIn(List<Integer> values) {
            addCriterion("SYSTEMSUPPORTMAN3 not in", values, "systemsupportman3");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman3Between(Integer value1, Integer value2) {
            addCriterion("SYSTEMSUPPORTMAN3 between", value1, value2, "systemsupportman3");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman3NotBetween(Integer value1, Integer value2) {
            addCriterion("SYSTEMSUPPORTMAN3 not between", value1, value2, "systemsupportman3");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman4IsNull() {
            addCriterion("SYSTEMSUPPORTMAN4 is null");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman4IsNotNull() {
            addCriterion("SYSTEMSUPPORTMAN4 is not null");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman4EqualTo(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN4 =", value, "systemsupportman4");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman4NotEqualTo(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN4 <>", value, "systemsupportman4");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman4GreaterThan(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN4 >", value, "systemsupportman4");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman4GreaterThanOrEqualTo(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN4 >=", value, "systemsupportman4");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman4LessThan(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN4 <", value, "systemsupportman4");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman4LessThanOrEqualTo(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN4 <=", value, "systemsupportman4");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman4In(List<Integer> values) {
            addCriterion("SYSTEMSUPPORTMAN4 in", values, "systemsupportman4");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman4NotIn(List<Integer> values) {
            addCriterion("SYSTEMSUPPORTMAN4 not in", values, "systemsupportman4");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman4Between(Integer value1, Integer value2) {
            addCriterion("SYSTEMSUPPORTMAN4 between", value1, value2, "systemsupportman4");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman4NotBetween(Integer value1, Integer value2) {
            addCriterion("SYSTEMSUPPORTMAN4 not between", value1, value2, "systemsupportman4");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman5IsNull() {
            addCriterion("SYSTEMSUPPORTMAN5 is null");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman5IsNotNull() {
            addCriterion("SYSTEMSUPPORTMAN5 is not null");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman5EqualTo(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN5 =", value, "systemsupportman5");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman5NotEqualTo(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN5 <>", value, "systemsupportman5");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman5GreaterThan(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN5 >", value, "systemsupportman5");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman5GreaterThanOrEqualTo(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN5 >=", value, "systemsupportman5");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman5LessThan(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN5 <", value, "systemsupportman5");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman5LessThanOrEqualTo(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN5 <=", value, "systemsupportman5");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman5In(List<Integer> values) {
            addCriterion("SYSTEMSUPPORTMAN5 in", values, "systemsupportman5");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman5NotIn(List<Integer> values) {
            addCriterion("SYSTEMSUPPORTMAN5 not in", values, "systemsupportman5");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman5Between(Integer value1, Integer value2) {
            addCriterion("SYSTEMSUPPORTMAN5 between", value1, value2, "systemsupportman5");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman5NotBetween(Integer value1, Integer value2) {
            addCriterion("SYSTEMSUPPORTMAN5 not between", value1, value2, "systemsupportman5");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman6IsNull() {
            addCriterion("SYSTEMSUPPORTMAN6 is null");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman6IsNotNull() {
            addCriterion("SYSTEMSUPPORTMAN6 is not null");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman6EqualTo(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN6 =", value, "systemsupportman6");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman6NotEqualTo(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN6 <>", value, "systemsupportman6");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman6GreaterThan(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN6 >", value, "systemsupportman6");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman6GreaterThanOrEqualTo(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN6 >=", value, "systemsupportman6");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman6LessThan(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN6 <", value, "systemsupportman6");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman6LessThanOrEqualTo(Integer value) {
            addCriterion("SYSTEMSUPPORTMAN6 <=", value, "systemsupportman6");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman6In(List<Integer> values) {
            addCriterion("SYSTEMSUPPORTMAN6 in", values, "systemsupportman6");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman6NotIn(List<Integer> values) {
            addCriterion("SYSTEMSUPPORTMAN6 not in", values, "systemsupportman6");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman6Between(Integer value1, Integer value2) {
            addCriterion("SYSTEMSUPPORTMAN6 between", value1, value2, "systemsupportman6");
            return (Criteria) this;
        }

        public Criteria andSystemsupportman6NotBetween(Integer value1, Integer value2) {
            addCriterion("SYSTEMSUPPORTMAN6 not between", value1, value2, "systemsupportman6");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYSTEMINFO
     *
     * @mbg.generated do_not_delete_during_merge Fri Mar 09 16:03:32 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYSTEMINFO
     *
     * @mbg.generated Fri Mar 09 16:03:32 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}