package com.james.ssm.service;

import com.james.ssm.po.Inspection;
import com.james.ssm.po.InspectionExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface InspectionService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECTION
     *
     * @mbg.generated Fri Mar 09 15:18:47 CST 2018
     */
    long countByExample(InspectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECTION
     *
     * @mbg.generated Fri Mar 09 15:18:47 CST 2018
     */
    int deleteByExample(InspectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECTION
     *
     * @mbg.generated Fri Mar 09 15:18:47 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECTION
     *
     * @mbg.generated Fri Mar 09 15:18:47 CST 2018
     */
    int insert(Inspection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECTION
     *
     * @mbg.generated Fri Mar 09 15:18:47 CST 2018
     */
    int insertSelective(Inspection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECTION
     *
     * @mbg.generated Fri Mar 09 15:18:47 CST 2018
     */
    List<Inspection> selectByExample(InspectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECTION
     *
     * @mbg.generated Fri Mar 09 15:18:47 CST 2018
     */
    Inspection selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECTION
     *
     * @mbg.generated Fri Mar 09 15:18:47 CST 2018
     */
    int updateByExampleSelective(@Param("record") Inspection record, @Param("example") InspectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECTION
     *
     * @mbg.generated Fri Mar 09 15:18:47 CST 2018
     */
    int updateByExample(@Param("record") Inspection record, @Param("example") InspectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECTION
     *
     * @mbg.generated Fri Mar 09 15:18:47 CST 2018
     */
    int updateByPrimaryKeySelective(Inspection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INSPECTION
     *
     * @mbg.generated Fri Mar 09 15:18:47 CST 2018
     */
    int updateByPrimaryKey(Inspection record);
}
